version: '3.8'

services:

  db:
    image: mongo:5.0
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME: user}
      MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD: user}
      MONGO_INITDB_DATABASE: registerup


  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGO_INITDB_ROOT_USERNAME: user}
        ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGO_INITDB_ROOT_PASSWORD: user}
        ME_CONFIG_MONGODB_SERVER: db
        ME_CONFIG_MONGODB_PORT: 27017



  app:
    build: .
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_PASSWORD:${MONGO_INITDB_ROOT_USERNAME: user}
      MONGO_USER:${MONGO_INITDB_ROOT_PASSWORD: user}
      MONGO_INITDB_DATABASE: registerup
    ports:
      - 3020:3020
