version: '3.8'

services:
  db:
    image: mongo:5.0
    volumes:
      - ./mongo-data:/data/db:z
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-user}

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - db
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-user}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-user}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME:-user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD:-user}

  app:
    build: .
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME:-user}
      MONGO_USER: ${MONGO_INITDB_ROOT_PASSWORD:-user}
    ports:
      - 8080:8070
